### ISSUE TITLE
Release new build of v0.6 supporting Python 3.7

### ISSUE THREAD

**Issue by robintw** [conda-forge/pysolar-feedstock#9]
I am the maintainer of Py6S, a package that depends on Pysolar. At the moment, Py6S depends on Pysolar v0.6, as that is the latest version that supports both Python 2 and Python 3.

However, the Pysolar v0.6 packages on conda-forge only support Python versions up to 3.6, so trying to install Py6S (and therefore Pysolar) in an environment with Python 3.7 requires downgrading Python to 3.6.

Is it possible to provide a new build of Pysolar 0.6 that is compatible with Python 3.7? Either as a specific Python 3.7 build, or ideally as a 'noarch' build that will be compatible with all Python versions.

(Like many projects, I am intending to drop Python 2 support shortly, but some users want to be able to install the same version of Py6S on Python 2 and 3, and the changes to the Pysolar API between versions 0.6 and 0.7/0.8 make this difficult)

**Comment by ocefpaf** [comment]
> Is it possible to provide a new build of Pysolar 0.6 that is compatible with Python 3.7? Either as a specific Python 3.7 build, or ideally as a 'noarch' build that will be compatible with all Python versions.

Sure. I you send a PR I'll create a branch for the v0.6 build and merge it.

**Comment by ocefpaf** [comment]
Done in #10
